services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sward
      POSTGRES_PASSWORD: sward
      POSTGRES_DB: trazabilidad_db
    ports:
      - "5436:5432"
  app:
    build: .
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://sward:sward@db:5432/trazabilidad_db
      ENVIRONMENT: development
    depends_on:
      - db
